# Generated by Django 6.0.4 on 2026-05-02 05:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the transaction",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount (up to 9,999,999,999.99)",
                        max_digits=12,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Food & Dining"),
                            ("transport", "Transport & Fuel"),
                            ("shopping", "Shopping & Lifestyle"),
                            ("bills", "Bills & Utilities"),
                            ("health", "Health & Medical"),
                            ("entertainment", "Entertainment"),
                            ("salary", "Salary & Income"),
                            ("freelance", "Freelance Income"),
                            ("investment", "Investments"),
                            ("other", "Miscellaneous"),
                        ],
                        default="other",
                        help_text="Type/category of the transaction",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("spent", "Spent"), ("credited", "Credited")],
                        help_text="Whether money was spent or credited",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description or notes about the transaction",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Date when the transaction occurred"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of this transaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
